### PR TITLE
Tahoe Studio Themes: Sync with Hawthorn

### PR DESCRIPTION
**Pull request by OmarIthawi**
Let's keep this in the theme now. Later on, we should migrate the functionality back to the platform and keep the theme for atheistic changes only.

Currently this pull request focuses on the following files:

```
cms/templates/base.html
cms/templates/container.html
cms/templates/course_outline.html
cms/templates/edit-tabs.html
cms/templates/howitworks.html
cms/templates/index.html
cms/templates/login.html
cms/templates/widgets/footer.html
cms/templates/widgets/header.html
```

Here's what I have done:

 - Get a fresh copy of the templates above from Hawthorn
 - Compare the differences between `edx-theme-customers:ficus/amc` and `edx-platform:open-release/fiucs.4`
 - Apply the same changes via some git magic and merge conflicts resolution

## How did I get those changes?
Most of the changes below should have been done in the edX Platform, so a `$ git merge open-release/hawthorn.master` can cause conflicts and then we would resolve them normally.

But the changes are in the theme and I have no idea what to do with them, so, I simulated a merge:

### First, summarize all Ficus changes in a single commit and call it `$APPSEMBLERIZE_COMMIT`

```
$ cd customer_specific
$ git checkout -b tmp/ficus-amc ficus/amc  # Make a temp branch out of Ficus's
# Get a fresh copy from the Ficus edX Platform
$ git ls-files -- 'cms/**.html' | xargs -L1 -I{} bash -c 'cat ~/work/tahoe-ficus/edx-platform/{} > {}'
$ git commit -a -m 'Get a fresh copy from Ficus'
$ git revert --no-edit HEAD
$ APPSEMBLERIZE_COMMIT=$(git rev-parse HEAD)
```

### Second, cherry pick that commit over a fresh Hawthorn files:
```
$ git checkout -b omar/hawthorn-updates hawthorn/tahoe
# Get a fresh copy from Hawthorn
$ git ls-files -- 'cms/**.html' | xargs -L1 -I{} bash -c 'cat ~/work/tahoe-hawthorn/edx-platform/{} > {}'
$ git commit -a -m 'Get a fresh copy from Hawthorn'
$ git push
$ git cherry-pick $APPSEMBLERIZE_COMMIT
# Resolve conflicts
$ git commit -m 'Tahoe Studio Themes: Sync with Hawthorn'
```

Stash the commits, push to GitHub, fix issues if any
Ask for review.

Voila! Your'e done! In the most stupid method ever!

### Why not `$ git apply`?

I tried it, it refused to work!

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(0) When I login to Studio, my user does not have permissions to create a course, only a library](https://trello.com/c/ZoR6er0f/3774-0-when-i-login-to-studio-my-user-does-not-have-permissions-to-create-a-course-only-a-library)

**Review by thraxil — APPROVED** [review]
Well, it looks fine to me. But I'm not that familiar with the themes or with mako syntax.

**Review by grozdanowski — APPROVED** [review]
@OmarIthawi I looked over the code and all seems fine. However, I cannot test this locally as Studio refuses to display the theme.

**Comment by OmarIthawi** [comment]
@grozdanowski I'll touch base with you on Slack to make sure it works on your device.

**Pull request merged**
