### PR TITLE
make email change emails custom domain aware

### PR DESCRIPTION
**Pull request by melvinsoft**

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@melvinsoft LGTM. I think this is better to be a platform change rather than keeping it here.

Sooner or later we'll get HTML emails, and we'll have to fix this again.

Having this in the platform will make git conflicts when we cherry-pick the HTML emails from upstream. Which is great! Since we'll know how to amend those cherry-picks. 

Putting it in the theme will make the bug "suddenly" appear "once in a while" from the perspective of our customers.

In reality, it's just that we forgot to add it in the correct place and didn't use `git` to it's fullest.

The other alternative, is to keep a list of hacks we did in the theme, so we can make sure we retain them from one release to another. 

Automated tests could be a solution, but for now I prefer to have it in the platform and let git do the work for us.

**Review by OmarIthawi — APPROVED** [review]
Thanks @melvinsoft, please check the comment above.

**Comment by melvinsoft** [comment]
@OmarIthawi Thanks for your review. I get your point and I agree. Since these aren't the only emails that we've in the theme, I'm creating a card to review and move them all to the core platform: https://trello.com/c/fhvAIZUH/3021-move-custom-domains-aware-emails-from-theme-to-the-core-platform-code

In the meantime I'm merging this PR.

**Comment by OmarIthawi** [comment]
Thanks @melvinsoft!

**Pull request merged**
