### PR TITLE
OU: Update logo

### PR DESCRIPTION
**Pull request by OmarIthawi**
OU says so.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(2) OU: Update OU's logo on the site](https://trello.com/c/EhcMypkk/3249-2-ou-update-ous-logo-on-the-site)

**Comment by OmarIthawi** [comment]
@grozdanowski Could you please take a look?

I did some slicing and GIMP filters to get this PR done. Probably you would've done it 10x times faster, but I hope that I saved you a bit of time. Would you mind actually running the theme locally and testing it?

**Review by grozdanowski — APPROVED** [review]
I checked it in Devstack - all's good. :)

**Comment by OmarIthawi** [comment]
Thanks @grozdanowski!

**Pull request merged**
