### PR TITLE
OU RTL fixes

### PR DESCRIPTION
**Pull request by OmarIthawi**
[(4) OU RTL issue](https://trello.com/c/8E9OwMe2/2581-4-ou-rtl-issue)

### TODO

 - [x] Fixes for normal text/html modules
 - [x] Fixes for inline discussion module
 - [x] Fixes for the discussion forum (not the inline ones)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(4) OU RTL issue](https://trello.com/c/8E9OwMe2/2581-4-ou-rtl-issue)

**Review by MHaton — CHANGES_REQUESTED** [review]
@OmarIthawi Currently missing elements used in that ["interesting" page](https://rtl-box.appsembler.com/courses/course-v1:edX+Demo+101/courseware/9fca584977d04885bc911ea76a9ef29e/8781ce2a8b03416aa2bd3b4362c6774a/1?activate_block_id=block-v1%3AedX%2BDemo%2B101%2Btype%40vertical%2Bblock%40fa27f1d83ba44ce6afeae2f33640db55) that are likely to come up:
th
td
li
blockquote
div
span

Not sure whether including div and span are good practice, but they're elements that can (and do, in the discussion component) contain text that isn't in p tags.

(woops, just realised I've done that wrong. Using github with other people is strange and new, sorry!)

**Comment by OmarIthawi** [comment]
Thanks @MHaton! Will take a look and let you know.

**Comment by OmarIthawi** [comment]
@MHaton please take another look. Now it's cryptic SASS and requires a compile. But it's self-contained and so far you can use an [online SASS compiler](https://www.sassmeister.com/) to do it for you.

**Comment by OmarIthawi** [comment]
@grozdanowski Care to take a quick look here?

**Review by MHaton — APPROVED** [review]

**Comment by grozdanowski** [comment]
@OmarIthawi looks good!

**Review by grozdanowski — APPROVED** [review]

**Pull request merged**
